language: node_js
node_js:
  - "0.11"
branches:
  only:
  - master
before_script:
    - 'curl https://raw.github.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.6.1 SOLR_CONFS="res/solrconf/schema.xml res/solrconf/solrconfig.xml res/solrconf/stopwords.txt res/solrconf/protwords.txt res/solrconf/synonyms.txt" bash'